controller_frequency: 5.0
TrajectoryPlannerROS:
  max_vel_x: 2.0
  min_vel_x: 0.05
  max_rotational_vel: 3.0
  min_rotational_vel: -3.0
  min_in_place_rotational_vel: 1.0
  escape_vel: -0.5
  acc_lim_theta: 0.75
  acc_lim_x: 0.50
  acc_lim_y: 0.50

  holonomic_robot: false
  yaw_goal_tolerance: 0.1
  xy_goal_tolerance: 0.2
  meter_scoring: true
  goal_distance_bias: 1.5
  path_distance_bias: 0.6
  sim_time: 2
  sim_granularity: 0.03
  heading_lookahead: 0.4
  oscillation_reset_dist: 0.25

  vx_samples: 8
  vtheta_samples: 20
  dwa: false

