obstacle_range: 2.5
raytrace_range: 3.0
footprint: [[-0.27, -0.25], [-0.27, 0.25], [0.27, 0.25], [0.27, -0.25]]
footprint_padding: 0.01
inflation_radius: 0.4
observation_sources: scan
scan: {data_type: LaserScan, topic: /scan, marking: true, clearing: true, frame_id: laser}

